name: ğŸš€ Build & Push Docker Image

on:
  push:
    branches: [master] # Use 'main' if your default branch is main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: â¬ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ³ Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ğŸ—ï¸ Build Docker image
        run: docker build -t ibrahimgulbutt/ci-cd-testing:latest .

      - name: ğŸ“¤ Push to DockerHub
        run: docker push ibrahimgulbutt/ci-cd-testing:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: ğŸš€ Deploy to Minikube
        run: kubectl set image deployment/flask-app flask-app=ibrahimgulbutt/ci-cd-testing:latest
